from typing import Optional
from fastapi import APIRouter, HTTPException, Query, status

from app.data.diagnosis_repository import diagnosis_repo
from app.data.metadata import validate_crop_disease
from app.models.diagnosis import (
    DiagnosisCreateRequest,
    DiagnosisListResponse,
    DiagnosisResponse,
)

router = APIRouter(
    prefix="/api/v1/diagnoses",
    tags=["Diagnoses"],
)


@router.post(
    "",
    response_model=DiagnosisResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Record a locally-computed plant disease diagnosis",
    description=(
        "Accept and store a diagnosis generated by the on-device MobileNetV3-Large FP16 TFLite model.\n\n"
        "**Offline-First Notice:** The diagnosis is generated locally on the Android device. "
        "This API is an optional synchronization/history endpoint and is not required for disease inference."
    ),
    responses={
        201: {"description": "Diagnosis successfully recorded on the backend companion."},
        400: {"description": "Invalid crop, disease ID out of range, or disease/crop mismatch."},
        422: {"description": "Validation error in request payload structure."},
    },
)
@router.post("/", include_in_schema=False, response_model=DiagnosisResponse, status_code=status.HTTP_201_CREATED)
def create_diagnosis(request: DiagnosisCreateRequest):
    """
    Record an on-device diagnosis after verifying metadata consistency
    against the 29-crop and 71-disease model catalog.
    """
    is_valid, error_msg, crop_ref, disease_ref = validate_crop_disease(
        crop_id=request.crop_id,
        disease_id=request.disease_id,
    )

    if not is_valid or crop_ref is None or disease_ref is None:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=error_msg or "Invalid crop or disease specification.",
        )

    record = diagnosis_repo.record_diagnosis(
        crop=crop_ref,
        disease=disease_ref,
        confidence=request.confidence,
        diagnostic_status=request.diagnostic_status.value,
        source=request.source,
        image_id=request.image_id,
        created_at=request.created_at,
    )

    return record


@router.get(
    "",
    response_model=DiagnosisListResponse,
    summary="List recorded diagnosis history",
    description="Retrieve a paginated list of recorded diagnoses, optionally filtered by crop.",
)
@router.get("/", include_in_schema=False, response_model=DiagnosisListResponse)
def list_diagnoses(
    crop_id: Optional[str] = Query(
        default=None,
        description="Optional filter by crop ID (e.g. 'tomato')",
        examples=["tomato"],
    ),
    limit: int = Query(
        default=50,
        ge=1,
        le=100,
        description="Maximum number of diagnosis records to return (1..100)",
    ),
):
    """Retrieve recorded diagnoses in reverse chronological order."""
    records = diagnosis_repo.list_diagnoses(crop_id=crop_id, limit=limit)
    return {
        "total": len(records),
        "diagnoses": records,
    }


@router.get(
    "/{diagnosis_id}",
    response_model=DiagnosisResponse,
    summary="Get a single diagnosis by ID",
    description="Retrieve details of a specific diagnosis record by its unique ID.",
    responses={
        200: {"description": "Diagnosis record found."},
        404: {"description": "Diagnosis ID not found."},
    },
)
def get_diagnosis(diagnosis_id: str):
    """Retrieve a single recorded diagnosis by ID."""
    record = diagnosis_repo.get_diagnosis_by_id(diagnosis_id)
    if not record:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Diagnosis '{diagnosis_id}' not found",
        )
    return record
